### ISSUE TITLE
ngseasy_initiate_project creates 'recursive' directories

### ISSUE THREAD

**Issue by olgamelnichuk** [KHP-Informatics/ngseasy#10]
Hello,
I've just noticed that after running ngseasy_initiate_project script a 'recursive' project structure is created... like path to my ngs_projects is recreated relatively from ngs_projects, 
e.g. /home/bob/ngs_projects/home/bob/ngs_projects/my_project

line 223 in ngseasy_initiate_project script prints $5/$1 from a tsv config which means: /home/bob/ngs_projects/my_project

line 230 in ngseasy_initiate_project script creates a directory: "${project_directory}/${PROJECTNAME}" which is "/home/bob/ngs_projects/home/bob/ngs_projects/my_project" according to script..

Also "-f" option in line 233 doesn't work for me...

**Comment by snewhouse** [comment]
Hi
Thanks for the bug report.
I'll fix and push by end of tomorrow at the latest
Cheers
Steve

**Comment by snewhouse** [comment]
Hi again - what day did you dowload the repo?
Cheers
Steve

**Comment by olgamelnichuk** [comment]
Hi Steve,
It was about 25 days ago. As I can see ngseasy_initiate_project was changed 1st of July and 30th of August. Both events (getting the source and posting this bug) happened just in between 1sth July and 30th of August. Taking in account August changes the lines of the bug are: 223 and 231.
Cheers,
Olga

**Comment by snewhouse** [comment]
Hi
Please can you try and re-create the error and send me the exact commands you ran + config file and the screen output?
Cheers
S

**Comment by olgamelnichuk** [comment]
Hi Steve,
Sure, here you are:
The command: ngseasy -c ngseasy_test.config.tsv -d /home/bob/ngs_projects
The config: https://github.com/KHP-Informatics/ngseasy/blob/c66d9b2db3df38c23e1ac820323e33604bd3fe87/test/ngseasy_test.config.tsv
and the log:
...
[Mon Aug 24 11:16:56 BST 2015]:[NGSEASY:1.0-r001]:[ngseasy_initiate_project]:Making [/home/bob/ngs_projects//home/bob/ngs_projects/Test_NGS] project directory:[bob]:[Linux exp-02 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux]
[Mon Aug 24 11:16:56 BST 2015]:[NGSEASY:1.0-r001]:[ngseasy_initiate_project]:CMD: awk 'NR >1 {print /-c/ngseasy_test.config.tsv}' ngseasy_test.config.tsv | sort | uniq > /home/bob/ngseasy/ngseasy_tmp/ProjectBySample_list:[bob]:[Linux exp-02 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux]
[Mon Aug 24 11:16:56 BST 2015]:[NGSEASY:1.0-r001]:[ngseasy_initiate_project]:/home/bob/ngs_projects/Test_NGS/NA12878] Exist:[bob]:[Linux exp-02 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux]
Cheers,
Olga

**Comment by snewhouse** [comment]
cheers. Will get back to you shortly

**Comment by snewhouse** [comment]
Hi

Please try:

``` bash
cd ngseasy
git checkout sjn_dev
sudo make INSTALLDIR="/home/bob/ngs_projects" updatescripts
```

and then try running the commands again...let me know if this works.

Cheers

S

**Comment by snewhouse** [comment]
PS. Very grateful for the testing and feedback!

**Comment by olgamelnichuk** [comment]
Hi Steve,

Thanks! I see that in sjn_dev branch it is already fixed... hope it will be merged soon.
Olga

**Comment by snewhouse** [comment]
Hi..its in `master` now :)
S

**Comment by snewhouse** [comment]
Me again...am looking for folks to get involved in the dev. Fancy joining the project?

**Comment by olgamelnichuk** [comment]
Hi Steve,

Thanks for the invitation. I'm actually pretty bad at bash programming.. and I'm not familiar with  bioinformatics tools much :-) but I'm experimenting with NGSeasy a lot trying to make it work in LSF cluster.. so could probably help with the testing..

Thanks,
Olga

**Comment by snewhouse** [comment]
ah...LSF...fun! ;)

Does your sys adim have examples of submitting jobs?

see: http://www.vub.ac.be/BFUCC/LSF/ (if you haven't already)

something like the following may work :- 

``` bash
bsub -q ${queue}  ngseasy  -c ngseasy_test.config.tsv -d /home/bob/ngs_projects
```

You will need documentation from your cluster admin on specific commands for defining compute limits etc (CPU, RAM...)

Unless you are running `snap` NGSeasy shouldn't require more than 14GB RAM (at its peak)...I've not really recorded full compute usage during a typical run

S

**Comment by olgamelnichuk** [comment]
Hi Steve,

Yep... exactly! However running everything on one node could take ages for a large experiment...  we are thinking about running separate docker jobs on different nodes (in case having too many samples).

Thanks,
Olga

**Comment by snewhouse** [comment]
ah. I get ya.
I was thinking a way around this is to make a separate config file for each sample, and then submit to the cluster.

eg:- 

``` bash
bsub ngseasy -c sample.1.config -d /home/user/ngs_projects
bsub ngseasy -c sample.2.config -d /home/user/ngs_projects
bsub ngseasy -c sample.3.config -d /home/user/ngs_projects
```

even loop...

``` bash
for i in {1..20}
do
   bsub ngseasy -c sample.${i}.config -d /home/user/ngs_projects
done
```

I used to do this with our SGE `qsub` cluster with great success.

Have fun playing around.
