### ISSUE TITLE
Wrong path to ngseasy_resources in ngseasy_trimmomatic script...

### ISSUE THREAD

**Issue by olgamelnichuk** [KHP-Informatics/ngseasy#11]
Hi Steve,

It seems you've quite recently changed the path to the references directory. So now it should be /ngs_projects/ngseasy_resources. But in some scripts I've noticed that another path is used.

Here are the details:

In ngseasy_trimmomatic (https://github.com/KHP-Informatics/ngseasy/blob/master/bin/ngseasy_trimmomatic) there is a code (line 467):
...
myresources=`dirname ${PROJECT_DIR}`
NGSResources="${myresources}/ngs_resources"
...
which says that I should have ngs_resources dir in the same level as ngs_projects (where PROJECT_DIR=/home/bob/ngs_projects)

and there is a corresponding mapping for docker volumes (line 477):
...
-v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
-v ${NGSResources}:/home/pipeman/ngs_resources \
...
however one of the parameters to the same docker run command (line 486): 

ILLUMINACLIP:${adapter_fa}:2:30:10:5:true \

contains a variable adpater_fa ('/home/pipeman/ngs_projects/ngseasy_resources/reference_genomes_b37/contaminant_list.fa')  which is an another path to reference genome...

Thank you,
Olga

**Comment by snewhouse** [comment]
Hi

I'll fix before end of day.....sorry....

S

**Comment by snewhouse** [comment]
Hi
please pull latest and give it a go
thanks again for the testing!
Cheers
S

**Comment by olgamelnichuk** [comment]
Wow! It was fast! 
thanks
Olga
