### ISSUE TITLE
varcaller:ensemble:HaplotypeCaller a typo

### ISSUE THREAD

**Issue by olgamelnichuk** [KHP-Informatics/ngseasy#12]
Hi Steve, 
in file: https://github.com/KHP-Informatics/ngseasy/blob/master/bin/ngseasy_variant_calling
in line: 1138
".gz" is forgotten, so it should be
tabix ${SOUTDocker}/vcf/${BAM_PREFIX}.raw.snps.indels.${VARCALLER}.vcf.gz

**Comment by snewhouse** [comment]
Hi

Corrected in `sjn_dev` branch.

Still testing GATV tools

Cheers

Steve

**Comment by snewhouse** [comment]
*GATK....I love typos!

**Comment by snewhouse** [comment]
done. for now
