### ISSUE TITLE
permission denied in fastqc container

### ISSUE THREAD

**Issue by olgamelnichuk** [KHP-Informatics/ngseasy#16]
when running ngseasy -c config.tsv -d /home/bob/ngs_projects the sample fastq folder doesn't have any fastqc results.. and trimmomatic step returns permission denied exception:

```
Exception in thread "main" java.io.FileNotFoundException: /home/pipeman/ngs_projects/TEST_PROJECT/TEST_SAMPLE/fastq/illumina.100bp.pe.wex.30x_1.fastq.gz (Permission denied)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at org.usadellab.trimmomatic.fastq.FastqParser.parse(FastqParser.java:127)
    at org.usadellab.trimmomatic.TrimmomaticPE.process(TrimmomaticPE.java:251)
    at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:498)
    at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:35)
```

If you look at the fastqc docker container output it has something like this:

```
$ docker logs 73ea98e292ad
Skipping '/home/pipeman/ngs_projects/TEST_PROJECT/TEST_SAMPLE/fastq/illumina.100bp.pe.wex.30x_1.fastq.gz' which didn't exist, or couldn't be read
Skipping '/home/pipeman/ngs_projects/TEST_PROJECT/TEST_SAMPLE/fastq/illumina.100bp.pe.wex.30x_2.fastq.gz' which didn't exist, or couldn't be read
```

So no fastqc output was generating.. after checking the file permissions I noticed that `ngseasy_initiate_fastqc` runs `chmod -R 776 ${sout}/*` at the very end which means that `fastq` sample folder has no "x" permission before the fastqc step is run, so the fastqc step is failed... 

I've also noticed that some other ngseasy steps (like bsqr and variant calling) do `chmod -R 777 ${OUT}/*` at the end so that after pipeline is finished all permissions are fine and it very hard to track where the problem is.. and why fastqc and trimmomatic are failed with permission denied..

**Comment by snewhouse** [comment]
Hi @olgamelnichuk 
Am in the process of refactoring NGSeasy and fixing these bugs. 
In the meantime pull or download the latest release of ngseasy, delete the fatqc and trimmomatic images and pull them down again. 
A quick fix would be to `chmod -R 777 ~/ngs_projects` - the sys adinms will hate us for it :)
sorry for the mess! 
More soon
Steve

**Comment by snewhouse** [comment]
Hi
Try pulling the fastqc container again.
Let me know

Was nice to meet breifly at Bio in Docker!
S
