### ISSUE TITLE
INSTALLDIR

### ISSUE THREAD

**Issue by bwkchee** [KHP-Informatics/ngseasy#17]
Just a minor quibble but might trip users up is that in the Readme, there is a misspelling of INSTALLDIR.  The Readme states "INTSALLDIR" is referenced but the Makefile expects a "INSTALLDIR".

**Comment by snewhouse** [comment]
argh - sorry! I am great with Typos! I will correct now
Note NGSeasy is undergoing some re-dev. Watch this space. Correcting typos and adding tools and removing boilerplate etc etc. Feel free to fork and contribute
