### ISSUE TITLE
ngseasy stopping in ngseasy_variant_calling step

### ISSUE THREAD

**Issue by dalloliogm** [KHP-Informatics/ngseasy#4]
I downloaded and installed ngseasy. 
The first steps seem to be running fine, but I get a warning saying that the config file doesn't exists, and the pipeline stops after a few seconds. 

The file /home/ubuntu/ngs_projects/config_files/ngseasy_test.config.tsv exists, and it is a copy of your test config file, downloaded during the `make testdata` step. I had to edit the file because it contained some ^M characters.

`sudo ngseasy -c /home/ubuntu/ngs_projects/config_files/ngseasy_test.config.tsv -d /home/ubuntu/ngs_projects/  -p 1  -f 1`
http://pastebin.com/wNnzRfbv

**Comment by snewhouse** [comment]
ah double nuts! 

You are our first real tester..and much valued!....anyways...a quick fix is to run ngseasy from the dir that contains the config file (I hope) so do

``` bash
cd  /home/ubuntu/ngs_projects/config_files/

sudo ngseasy -c ngseasy_test.config.tsv -d /home/ubuntu/ngs_projects -p 1 -f 1
```

but first, update the config file so that the **PROJECT_DIR** is  `/home/ubuntu/ngs_projects`

sorry about the dodgy config file - produced on a Mac! dos2unix it.

Hope this works - gotta love the teething problems.

**Comment by snewhouse** [comment]
PS. re-run the whole thing. Reove output from Fastqc, trimm, aligner etc etc and start it up again. The project dirs should have been built so you should just be able to run without the -p and -f flags:-

``` bash
cd  /home/ubuntu/ngs_projects/config_files/

sudo ngseasy -c ngseasy_test.config.tsv -d /home/ubuntu/ngs_projects
```

**Comment by dalloliogm** [comment]
It seems that the ngs_projects/Test_NGS folder has not been created. I can find it in the raw_fastq folder, however it is missing some subfolders. For example, it is complaning that it can't find the folder /home/ubuntu/ngs_projects/raw_fastq/Test_NGS/NA12878 in the ngseasy_fastq step.

**Comment by snewhouse** [comment]
hi sorry again. 

try running 

``` bash
#####################
# move to config file location 
#
cd /home/ubuntu/ngs_projects/config_file
```

``` bash
####################
# set up dirs
#
ngseasy_initiate_project \
-c ngseasy_test.config.tsv \
-d /home/ubuntu/ngs_projects 
```

``` bash
####################
# set up fastq
#
ngseasy_initiate_fastq \
-c  ngseasy_test.config.tsv \
-d /home/ubuntu/ngs_projects
```

``` bash
####################
# run ngseasy
#
 ngseasy \
-c ngseasy_test.config.tsv \
-d /home/ubuntu/ngs_projects
```

this should set up the correct directory and then set up fastq the run ngseasy 

let me know 

if this doesn't work, I will sort it out and push fixes by end of Sunday 

sorry for the faffing 

cheers again

**Comment by dalloliogm** [comment]
Sorry for not answering before, but I was busy traveling and organizing other stuff.
Thanks for the changes. I'll update the repository and try again tomorrow. In any case, don't worry too much about the workshop: I have the impression that the students will need a more basic introduction first, e.g. on how to install software on linux and so on. I'll let you know how it goes ;-)

**Comment by snewhouse** [comment]
@dalloliogm no probs - your testing has been valuable! Try again when you get the chance..we really need other folks to have a play and get involved in dev. Hope the course prep all good
