### ISSUE TITLE
Bash script errors

### ISSUE THREAD

**Issue by natacourby** [KHP-Informatics/ngseasy#6]
Hi,
I'm Natalja from EMBL-EBI. We are trying to run NGSeasy pipeline on our Embassy Cloud and I found someissues. Would like to notice that I'm not a bash script expert, so may be I just misunderstood smth or there are differences in scripts execution on different linux distributions. 
We are using CentOS as NFS server where NGSeasy scripts are stored and some of them are running (project initiation scripts) and Ubuntu 14.04 for docker machines.

Here is my list:
1) variable VERSION is missed error almost in all scripts. I've fixed it by renaming VERSION to NGSEASYVERSION (from config file) 
2) function logger_ngseasy()  in some of the scripts was causing an error because it is called from inside the script(s) with only one argument passed (at least as I understood). So I've changed it by adding default value for the second argument "mylogfile".
3) I've commented out in all scripts the following line: 
 #logger_ngseasy "[${NGSEASY_STEP}]:CMD: awk 'NR >1 {print $5"/"$1}' ${config_tsv} | sort | uniq > ${HOME}/ngseasy_tmp/Project_list" ${config_run_log}
since it was causing errors.
4) not sure that it is an issue, but in order to run scripts from NFS server I've changed the call of the scripts from /bin/bash  <script name> to bash <path to the scripts>/<script name>. For example, /bin/bash  ngseasy_initiate_project ... was changed to bash /nfs/ngseasy/bin/ngseasy_initiate_project
5) ngseasy_initiate_project:  in my case during reading of file -f argument is not available, so I've changed:
 "while read -f PROJECTNAME" to "while read PROJECTNAME"
6) ngseasy_fastqc: all lines similar to this one if [[ "${GENOMEBUILD}" -eq "b37" ]]; I've changed to if [[ "${GENOMEBUILD}" = "b37" ]]; since "=" is used for string comparison and "-eq" caused error.

I suppose that's it for now. Sorry if some of the issues are relevant only for our environment. 

Also it could be nice to discuss with you parallelization questions. If I've got everything correctly then only fastqc jobs are running in parallel. All other steps go one by one. We are creating docker cluster so may be we can try to find effective solution for the alignment and other steps together with you? 

-Natalja

**Comment by snewhouse** [comment]
Hi
Thanks for testing

NGSeasy is under heavy dev - I will look into these

when did you clone the repo? do a `git pull` to update and note that the version is now `1.0-r001`

run `sudo make dockerimages && sudo make install` to get new builds...

I'm hoping to have these minor bugs worked out in the next week or so

Also are you running the scripts outside of the main script `ngseasy`

The new version  - everything is run by calling `ngseasy -c <> -d <>`

Let me know how you get on

Cheers

Steve

**Comment by snewhouse** [comment]
ps. can you send some of the log file or screen output?

Cheers

Steve & Amos

**Comment by natacourby** [comment]
Sure. First thing tomorrow morning. Will send the scripts, screen output and logs by e-mail.

**Comment by snewhouse** [comment]
Great - thanks
Can you also give us an indication of how long it took to set up and how easy or hard it was to follow the instructions etc
Any and all feed back is valuable!
If you have suggestions, feel free to send them through
Cheers
Steve & Amos

**Comment by snewhouse** [comment]
Hi

Best to re clone next week  and start from the beginning.

Made some changes, that I am testing now.

I will keep you informed

Best

Steve & Amos

**Comment by natacourby** [comment]
I've pulled the latest version of ngseasy and it is running now. 
The list of issues is really reduced. All I have to do to make it run in our environment was:
1) /bin/bash to bash /nfs...
2) /nfs/ngseasy/bin/01JUL15/ngseasy_initiate_project: line 225: read: -f: invalid option
I've removed -f

Logs are coming. Sorry for the delay.

**Comment by afolarin** [comment]
/bin/bash: ngseasy_trimmomatic: No such file or directory
[Wed Jul 1 14:48:34 BST 2015]:[NGSEASY:1.0-r001]:[ngseasy]:Calling ngseasy_alignment:[ansible]:[Linux natalja-test3 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux]
/bin/bash: ngseasy_alignment: No such file or directory
[Wed Jul 1 14:48:34 BST 2015]:[NGSEASY:1.0-r001]:[ngseasy]:Calling ngseasy_realn:[ansible]:[Linux natalja-test3 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux]
/bin/bash: ngseasy_realn: No such file or directory

sounds like a pathing issue. the makefile was meant to path these for you perhaps something went wrong in the setup?
try :
$ which  ngseasy_alignment

in the makefile edit the TARGET_BIN so it is appropriate for your setup
