### ISSUE TITLE
About downloading time and running errors

### ISSUE THREAD

**Issue by StudySomeCode** [KHP-Informatics/ngseasy#8]
Hi,

In readme, it says:

Install can take a while, 1-2 hours, so go get a coffee
just chill...
if your network is bad...then who knows how long...
still..just chill...

But the command 

make INTSALLDIR="/home/ec2-user" all 

takes more than a week to download. The downloading speed for me is about 3MB/s, is that normal?

And another question, when I tried to run

ngseasy -c ngseasy_test.config.tsv -d /home/ec2-user/ngs_projects

I got some errors in run log as:

Exception in thread "main" java.io.FileNotFoundException: /home/pipeman/ngs_projects/Test_NGS/NA12878/fastq/illumina.100bp.pe.wex.30x_1.fastq.gz (Permission denied)^M
        at java.io.FileInputStream.open(Native Method)^M
        at java.io.FileInputStream.<init>(FileInputStream.java:146)^M
        at org.usadellab.trimmomatic.fastq.FastqParser.parse(FastqParser.java:127)^M
        at org.usadellab.trimmomatic.TrimmomaticPE.process(TrimmomaticPE.java:251)^M
        at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:498)^M
        at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:35)

I run the command with sudo so I do not know why there is permission denied exception.
The file list in the exception is in /home/root/*, is that the problem?

And at the end of run log, it says:

[Sat Aug 8 22:03:07 UTC 2015]:[NGSEASY:1.0-r001]:[ngseasy_variant_calling]:ERROR:Can not find required BAM File for Variant Calling:[root]:[Linux ip-172-31-23-78 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux]

Thank you very much!

**Comment by snewhouse** [comment]
Hi

Sorry for the delay - just back from Annual Leave.

That download time sounds excessive. Not sure what is going on there.

When did you download the git repo and what are you running this on (Amazon EC2 or local machine)?

Remove/Delete everything and get ngseasy again...

Remove docker images 

``` bash
sudo docker rmi -f $(docker images | grep compbio | awk '{print $3}') 
sudo docker rm -f $(docker ps -a | grep -v CONTAINER | awk '{print $1}') 
```

Try doing the install in steps...

Get NGSeasy

``` bash
## get it again
git clone https://github.com/KHP-Informatics/ngseasy

cd ngseasy
```

Install in steps

``` bash
## make sure you set your INTSALLDIR
sudo make INTSALLDIR="/home/ec2-user" install 

make  INTSALLDIR="/home/ec2-user" ngsprojectdir

make  INTSALLDIR="/home/ec2-user" dockerimages

make  INTSALLDIR="/home/ec2-user" b37

make  INTSALLDIR="/home/ec2-user" testdata
```

If permission problems persist, try chmod'ing your working and install directories ie `chmod -R 777 /home/PATH/TO/DIR` 

Cheers

Steve

**Comment by snewhouse** [comment]
PS. Download speed is a major issue.
Our connections run at > 800 Mbit/s

**Comment by snewhouse** [comment]
Hi closing this. send another bug report if you get any.
